#!/bin/bash
resx=`xdpyinfo  | grep dimensions| grep -o " [0-9]\+x[0-9]\+ " | grep -o "[0-9]\+"| head -n 1`
resy=`xdpyinfo  | grep dimensions| grep -o " [0-9]\+x[0-9]\+ " | grep -o "[0-9]\+"| head -n 2| tail -n 1`
y=$((4*resy/5))
resy=$((resy/5))
#echo $resx
#echo $resy
gsettings set org.onboard.window docking-enabled true
gsettings set org.onboard.window.landscape dock-expand true
gsettings set org.onboard.window force-to-top true
onboard -s $resx'x'$resy -x 0 -y $y
